[package]
name = "hawk"
version = "0.1.0"
edition = "2018"
build = "src/build.rs"

[build-dependencies]
cc="*"

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tree-sitter = "0.20.1"
