[package]
name = "hawk-terminal"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hawk = { path = "../hawk" }
crossterm = "0.22"
log = "0.4.14"
simplelog = "^0.10.0"